# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: NGINX Proxy Manager 2
version: "1.0.0"
slug: proxymanage
description: "Manage Nginx proxy hosts with a simple, powerful interface"
arch:
  - aarch64
  - amd64
  - armv7
url: "https://github.com/masrim2000/addon-nginx-proxy-manager2/proxy-manager"
webui: http://[HOST]:[PORT:81]
startup: services
init: false
hassio_api: true
ports:
  80/tcp: 80
  81/tcp: 81
  443/tcp: 443
  21114/tcp: 21114
  21115/tcp: 21115
  21116/udp: 21116
  21117/tcp: 21117
  21118/tcp: 21118
  21119:tcp: 21119
map:
  - addon_config:rw
backup_exclude:
  - "*/logs"
